name: oauth_example
description: A shelf example for oauth authentication providers.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5
  shelf:
  oauth2: ^2.0.1
  pointycastle: ^3.6.2
  shelf_web_socket: ^1.0.0
  web_socket_channel: ^2.3.0
  shelf_hotreload: ^1.4.0
  oauth:
    path: ..

dev_dependencies:
  test: ^1.23.1
  very_good_analysis: ^4.0.0
