name: oauth
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5
  oauth2: ^2.0.1
  crypto: ^3.0.2
  openid_client: ^0.4.7
  jose: ^0.3.3
  oxidized: ^5.3.0
  argon2: ^1.0.1
  meta: ^1.9.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^4.0.0
